CREATE TABLE Sprints
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    DATE_START DATE NOT NULL,
    DATE_END DATE NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    STATUS ENUM('PENDING', 'IN_PROGRESS', 'FINISHED', 'CANCELED') NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE UserStories
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    POINTS INTEGER NOT NULL,
    STATUS ENUM('TO_DO', 'IN_PROGRESS', 'REVIEW', 'DONE') NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE SprintUserStory
(
    SPRINT_ID BIGINT NOT NULL,
    USER_STORY_ID BIGINT NOT NULL,
    FOREIGN KEY (`SPRINT_ID`)
        REFERENCES `Sprints` (`id`),
    FOREIGN KEY (`USER_STORY_ID`)
        REFERENCES `UserStories` (`id`),
    PRIMARY KEY (SPRINT_ID, USER_STORY_ID)
);
