CREATE TABLE Sprints
(
    ID serial PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    DATE_START DATE NOT NULL,
    DATE_END DATE NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    STATUS ENUM('PENDING', 'IN_PROGRESS', 'FINISHED', 'CANCELED') NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE User_Stories
(
    ID serial PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(512) NOT NULL,
    POINTS INTEGER,
    STATUS ENUM('TO_DO', 'IN_PROGRESS', 'REVIEW', 'DONE') NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE Sprint_User_Story
(
    SPRINT_ID BIGINT NOT NULL,
    USER_STORY_ID BIGINT NOT NULL,
    FOREIGN KEY (`SPRINT_ID`)
        REFERENCES `Sprints` (`id`),
    FOREIGN KEY (`USER_STORY_ID`)
        REFERENCES `User_Stories` (`id`),
    PRIMARY KEY (SPRINT_ID, USER_STORY_ID)
);

CREATE TABLE Attachments
(
    ID serial PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    FILE varbinary(max)
);

CREATE TABLE User_Story_Attachments
(
    USER_STORY_ID BIGINT NOT NULL,
    ATTACHMENT_ID BIGINT NOT NULL,
    FOREIGN KEY (`USER_STORY_ID`)
        REFERENCES `User_Stories` (`id`),
    FOREIGN KEY (`ATTACHMENT_ID`)
        REFERENCES `Attachments` (`id`),
    PRIMARY KEY (USER_STORY_ID, USER_STORY_ID)
);